// books-data.js – centralized book database
const booksData = [
    // ═══════════════════════════════════════════
    // 📚 الروايات
    // ═══════════════════════════════════════════
    {
        id: 1,
        title: "ليطمئن قلبي",
        author: "أدهم الشرقاوي",
        price: "120 جنيه",
        oldPrice: "160 جنيه",
        discount: "25%",
        image: "BOKS/صفحه الكتب/6bb4e0de-8a47-446e-9f00-e3356bf85a8c-192X290.png",
        categories: ["روايات"],
        rating: 4,
        reviews: 270,
        description: "رواية تأخذك في رحلة إيمانية وفلسفية للإجابة عن تساؤلات الروح والبحث عن الطمأنينة في عالم صاخب.",
        publisher: "دار كلمات",
        pages: 340,
        year: 2020,
        language: "العربية",
        isbn: "994-2244668800"
    },
    {
        id: 2,
        title: "واشتعل القلب حزنا",
        author: "أحمد هشام",
        price: "45 جنيه",
        oldPrice: "90 جنيه",
        discount: "50%",
        image: "BOKS/images.jpg",
        categories: ["روايات"],
        rating: 5,
        reviews: 120,
        description: "قصة إنسانية مؤثرة تتناول مشاعر الفقد والأمل والقدرة على البدء من جديد بعد الصدمات.",
        publisher: "دار النور",
        pages: 210,
        year: 2022,
        language: "العربية",
        isbn: "994-1112223334"
    },
    {
        id: 3,
        title: "واشتعل القلب عشقا",
        author: "ورده ايوب",
        price: "55 جنيه",
        oldPrice: "110 جنيه",
        discount: "50%",
        image: "BOKS/صور كتب مشابه/1859397911808e8d2359072dcd420763.jpg.webp",
        categories: ["روايات"],
        rating: 5,
        reviews: 190,
        description: "رواية رومانسية كلاسيكية تدور أحداثها في أجواء درامية تجمع بين الحب والتضحية والصراعات العائلية.",
        publisher: "دار الأحلام",
        pages: 280,
        year: 2021,
        language: "العربية",
        isbn: "994-5556667778"
    },
    {
        id: 4,
        title: "في قلبي أنثى عبرية",
        author: "خولة حمدي",
        price: "65 جنيه",
        oldPrice: "95 جنيه",
        discount: "32%",
        image: "BOKS/images (1).jpg",
        categories: ["روايات"],
        rating: 5,
        reviews: 430,
        description: "رواية تجمع بين أحداث تاريخية وقصة حب مستحيلة تتخطى حدود الديانات والثقافات، تأخذك في رحلة مشوقة بين تونس وفلسطين.",
        publisher: "دار كيان",
        pages: 350,
        year: 2012,
        language: "العربية",
        isbn: "994-7788990011"
    },
    {
        id: 5,
        title: "ساق البامبو",
        author: "سعود السنعوسي",
        price: "70 جنيه",
        oldPrice: "100 جنيه",
        discount: "30%",
        image: "BOKS/images (2).jpg",
        categories: ["روايات"],
        rating: 5,
        reviews: 560,
        description: "رواية حازت على الجائزة العالمية للرواية العربية (البوكر)، تروي قصة شاب نصف كويتي نصف فلبيني يبحث عن هويته بين عالمين مختلفين.",
        publisher: "الدار العربية للعلوم",
        pages: 396,
        year: 2012,
        language: "العربية",
        isbn: "994-1234509876"
    },
    {
        id: 6,
        title: "الأسود يليق بك",
        author: "أحلام مستغانمي",
        price: "75 جنيه",
        oldPrice: "110 جنيه",
        discount: "32%",
        image: "BOKS/images (3).jpg",
        categories: ["روايات"],
        rating: 4,
        reviews: 380,
        description: "رواية تمزج بين الحب والفن والسياسة بأسلوب شعري ساحر، في قصة عن امرأة تعيش بين باريس والجزائر.",
        publisher: "دار نوفل",
        pages: 320,
        year: 2010,
        language: "العربية",
        isbn: "994-6677889900"
    },
    {
        id: 7,
        title: "رحلة ابن فطومة",
        author: "نجيب محفوظ",
        price: "60 جنيه",
        oldPrice: "85 جنيه",
        discount: "29%",
        image: "BOKS/images (4).jpg",
        categories: ["روايات"],
        rating: 5,
        reviews: 290,
        description: "رحلة رمزية يقوم بها قنديل بن فطومة عبر بلدان خيالية يبحث فيها عن المدينة الفاضلة، في ثوب أدبي فلسفي بديع.",
        publisher: "دار الشروق",
        pages: 180,
        year: 1983,
        language: "العربية",
        isbn: "994-3322110099"
    },
    {
        id: 8,
        title: "ثلاثية غرناطة",
        author: "رضوى عاشور",
        price: "85 جنيه",
        oldPrice: "120 جنيه",
        discount: "29%",
        image: "BOKS/images (5).jpg",
        categories: ["روايات"],
        rating: 5,
        reviews: 610,
        description: "ملحمة أدبية تروي سقوط الأندلس من خلال عائلة عربية تعيش في غرناطة، وتوثق لحظة حضارية فارقة بأسلوب مؤثر.",
        publisher: "دار الشروق",
        pages: 550,
        year: 1994,
        language: "العربية",
        isbn: "994-4455667788"
    },

    // ═══════════════════════════════════════════
    // 🕋 الكتب الدينية
    // ═══════════════════════════════════════════
    {
        id: 9,
        title: "يأجوج ومأجوج",
        author: "أحمد علي",
        price: "60 جنيه",
        oldPrice: "80 جنيه",
        discount: "25%",
        image: "BOKS/صفحه الكتب/f11982e9-ef6a-4537-b529-32b457feef11-192X290.png",
        categories: ["كتب دينية"],
        rating: 4,
        reviews: 85,
        description: "دراسة شاملة وعميقة حول قصة يأجوج ومأجوج من المنظور الديني والتاريخي، مع استعراض للآراء المختلفة حول هويتهم ومكانهم وتوقيت خروجهم.",
        publisher: "دار الهلال",
        pages: 280,
        year: 2019,
        language: "العربية",
        isbn: "994-0987654321"
    },
    {
        id: 10,
        title: "التربية والتعليم في الإسلام",
        author: "د. خالد العمر",
        price: "80 جنيه",
        oldPrice: "100 جنيه",
        discount: "20%",
        image: "BOKS/صفحه الكتب/aebfd59d-5b33-41e5-87ed-ff47a381ea0f-192X290.png",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 210,
        description: "يتناول الكتاب أسس التربية والتعليم في المنظور الإسلامي، وكيفية تطبيقها في العصر الحديث لبناء جيل مثقف ومتمسك بقيمه.",
        publisher: "دار القلم",
        pages: 310,
        year: 2021,
        language: "العربية",
        isbn: "994-5566778899"
    },
    {
        id: 11,
        title: "عبقرية محمد ﷺ",
        author: "عباس محمود العقاد",
        price: "110 جنيه",
        oldPrice: "150 جنيه",
        discount: "27%",
        image: "BOKS/صفحه الكتب/7df540eb-3120-4023-844c-1b647e88dc79-192X290.png",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 500,
        description: "تحليل نفسي وعقلي لشخصية النبي محمد صلى الله عليه وسلم، يبرز جوانب العظمة البشرية والقيادة والرحمة.",
        publisher: "دار الشروق",
        pages: 320,
        year: 2011,
        language: "العربية",
        isbn: "994-1133557799"
    },
    {
        id: 12,
        title: "لا تحزن",
        author: "عائض القرني",
        price: "55 جنيه",
        oldPrice: "80 جنيه",
        discount: "31%",
        image: "BOKS/images (6).jpg",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 720,
        description: "كتاب يبعث الأمل والتفاؤل في النفوس، يقدم وصفات إيمانية وعملية للتعامل مع الهموم والأحزان من منظور إسلامي.",
        publisher: "مكتبة العبيكان",
        pages: 480,
        year: 2003,
        language: "العربية",
        isbn: "994-9900112233"
    },
    {
        id: 13,
        title: "صحيح البخاري - مختصر",
        author: "الإمام البخاري",
        price: "130 جنيه",
        oldPrice: "180 جنيه",
        discount: "28%",
        image: "BOKS/images (7).jpg",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 950,
        description: "مختصر لأصح كتب الأحاديث النبوية الشريفة، يضم أهم الأحاديث المروية عن النبي ﷺ في العبادات والمعاملات والأخلاق.",
        publisher: "دار ابن كثير",
        pages: 600,
        year: 2000,
        language: "العربية",
        isbn: "994-1122334400"
    },
    {
        id: 14,
        title: "رياض الصالحين",
        author: "الإمام النووي",
        price: "90 جنيه",
        oldPrice: "130 جنيه",
        discount: "31%",
        image: "BOKS/Dk5AVzvUUAIw8y5.jpg",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 880,
        description: "مجموعة من الأحاديث النبوية الصحيحة مرتبة في أبواب تغطي جميع جوانب حياة المسلم من عبادات ومعاملات وأخلاق.",
        publisher: "دار السلام",
        pages: 520,
        year: 1999,
        language: "العربية",
        isbn: "994-5544332211"
    },
    {
        id: 15,
        title: "فقه السنة",
        author: "سيد سابق",
        price: "100 جنيه",
        oldPrice: "140 جنيه",
        discount: "29%",
        image: "BOKS/fbb16d224565137.Y3JvcCwxOTI0LDE1MDUsNDM4LDI5NQ.jpg",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 650,
        description: "موسوعة فقهية شاملة تقدم الأحكام الشرعية بأسلوب ميسر مع الاستدلال من الكتاب والسنة، مرجع أساسي لكل مسلم.",
        publisher: "دار الفتح",
        pages: 740,
        year: 1998,
        language: "العربية",
        isbn: "994-6655443322"
    },
    {
        id: 16,
        title: "قصص الأنبياء",
        author: "ابن كثير",
        price: "70 جنيه",
        oldPrice: "95 جنيه",
        discount: "26%",
        image: "BOKS/6284f319e2413f159ddfe04db796654b.jpg",
        categories: ["كتب دينية"],
        rating: 5,
        reviews: 780,
        description: "سرد مفصل ومشوق لقصص الأنبياء والمرسلين من آدم عليه السلام إلى خاتم الأنبياء محمد ﷺ، مستندًا إلى القرآن والأحاديث.",
        publisher: "دار الإيمان",
        pages: 450,
        year: 2005,
        language: "العربية",
        isbn: "994-7766554433"
    },

    // ═══════════════════════════════════════════
    // 🎯 تنمية بشرية
    // ═══════════════════════════════════════════
    {
        id: 17,
        title: "العادات السبع للناس الأكثر فعالية",
        author: "ستيفن كوفي",
        price: "85 جنيه",
        oldPrice: "120 جنيه",
        discount: "29%",
        image: "BOKS/_640x_bac78f3d53907a5d308433bf2b5bcf3ea397a4a057ff1d5554b45f1c76d01438.jpg",
        categories: ["تنمية بشرية"],
        rating: 5,
        reviews: 1200,
        description: "من أشهر كتب التنمية البشرية عالمياً، يقدم سبع عادات أساسية لتحقيق النجاح الشخصي والمهني بأسلوب عملي ومنهجي.",
        publisher: "مكتبة جرير",
        pages: 380,
        year: 2004,
        language: "العربية",
        isbn: "994-8877665544"
    },
    {
        id: 18,
        title: "قوة العقل الباطن",
        author: "جوزيف ميرفي",
        price: "50 جنيه",
        oldPrice: "75 جنيه",
        discount: "33%",
        image: "BOKS/images (1).jpg",
        categories: ["تنمية بشرية"],
        rating: 4,
        reviews: 890,
        description: "يكشف الكتاب أسرار العقل الباطن وقدراته الخارقة في تحقيق الأهداف والشفاء والنجاح، مع تمارين عملية لاستثمار طاقاته.",
        publisher: "دار الهلال",
        pages: 260,
        year: 2008,
        language: "العربية",
        isbn: "994-9988776600"
    },
    {
        id: 19,
        title: "فن اللامبالاة",
        author: "مارك مانسون",
        price: "60 جنيه",
        oldPrice: "90 جنيه",
        discount: "33%",
        image: "BOKS/images (2).jpg",
        categories: ["تنمية بشرية"],
        rating: 4,
        reviews: 1050,
        description: "كتاب يتحدى النظرة التقليدية للتفاؤل ويقدم فلسفة واقعية لحياة أفضل، من خلال اختيار ما يستحق الاهتمام فعلاً.",
        publisher: "دار التنوير",
        pages: 220,
        year: 2017,
        language: "العربية",
        isbn: "994-1100223344"
    },
    {
        id: 20,
        title: "الأب الغني والأب الفقير",
        author: "روبرت كيوساكي",
        price: "75 جنيه",
        oldPrice: "105 جنيه",
        discount: "29%",
        image: "BOKS/images (3).jpg",
        categories: ["تنمية بشرية"],
        rating: 5,
        reviews: 1400,
        description: "من أكثر الكتب مبيعاً في العالم عن الثقافة المالية، يقارن بين طريقتين في التفكير حول المال والاستثمار والثروة.",
        publisher: "مكتبة جرير",
        pages: 336,
        year: 2000,
        language: "العربية",
        isbn: "994-2211334455"
    },
    {
        id: 21,
        title: "كيف تكسب الأصدقاء وتؤثر في الناس",
        author: "ديل كارنيجي",
        price: "55 جنيه",
        oldPrice: "80 جنيه",
        discount: "31%",
        image: "BOKS/images (4).jpg",
        categories: ["تنمية بشرية"],
        rating: 5,
        reviews: 1680,
        description: "دليل عملي لبناء علاقات ناجحة والتأثير في الآخرين بأسلوب إيجابي، من أكثر الكتب تأثيراً في تاريخ التنمية البشرية.",
        publisher: "مكتبة جرير",
        pages: 288,
        year: 1998,
        language: "العربية",
        isbn: "994-3322445566"
    },
    {
        id: 22,
        title: "قوة التفكير الإيجابي",
        author: "نورمان فينسنت بيل",
        price: "45 جنيه",
        oldPrice: "70 جنيه",
        discount: "36%",
        image: "BOKS/images (5).jpg",
        categories: ["تنمية بشرية"],
        rating: 4,
        reviews: 560,
        description: "يقدم الكتاب تقنيات عملية لتحويل الأفكار السلبية إلى إيجابية وكيف يؤثر التفكير الإيجابي في تحقيق النجاح والسعادة.",
        publisher: "مكتبة العبيكان",
        pages: 240,
        year: 2006,
        language: "العربية",
        isbn: "994-4433556677"
    },
    {
        id: 23,
        title: "أيقظ العملاق الذي بداخلك",
        author: "أنتوني روبنز",
        price: "90 جنيه",
        oldPrice: "130 جنيه",
        discount: "31%",
        image: "BOKS/images (6).jpg",
        categories: ["تنمية بشرية"],
        rating: 5,
        reviews: 920,
        description: "دليل شامل للسيطرة على حياتك العاطفية والجسدية والمالية والمهنية، من خلال استراتيجيات عملية مجربة لتحقيق التميز.",
        publisher: "مكتبة جرير",
        pages: 540,
        year: 2010,
        language: "العربية",
        isbn: "994-5544667788"
    },
    {
        id: 24,
        title: "العقل الباطن - أسرار القوة الداخلية",
        author: "هاري لورين",
        price: "40 جنيه",
        oldPrice: "65 جنيه",
        discount: "38%",
        image: "BOKS/images (7).jpg",
        categories: ["تنمية بشرية"],
        rating: 4,
        reviews: 440,
        description: "اكتشف كيف يعمل عقلك الباطن وتعلم كيف توجهه لتحقيق أهدافك في الحياة من خلال تقنيات مثبتة علميًا.",
        publisher: "دار الهلال",
        pages: 200,
        year: 2014,
        language: "العربية",
        isbn: "994-6655778899"
    },

    // ═══════════════════════════════════════════
    // ⏳ التاريخ
    // ═══════════════════════════════════════════
    {
        id: 25,
        title: "تاريخ الدولة العثمانية",
        author: "أوزتونا",
        price: "50 جنيه",
        oldPrice: "100 جنيه",
        discount: "50%",
        image: "BOKS/صفحه الكتب/f29678a9-69b6-4a94-a9ac-c8252ae87c58-192X290.png",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 140,
        description: "يستعرض تاريخ واحدة من أطول الإمبراطوريات عمرًا وأكثرها تأثيرًا في العالم، من نشأتها حتى سقوطها.",
        publisher: "دار النور للنشر",
        pages: 350,
        year: 2017,
        language: "العربية",
        isbn: "994-1234567890"
    },
    {
        id: 26,
        title: "تاريخ المشرق",
        author: "د. سامي محمود",
        price: "70 جنيه",
        oldPrice: "90 جنيه",
        discount: "22%",
        image: "BOKS/صفحه الكتب/ee3334ca-8190-4572-b63b-1bb805d81c2e-192X290.png",
        categories: ["تاريخ"],
        rating: 3,
        reviews: 45,
        description: "كتاب يتناول تاريخ الحضارات القديمة في منطقة المشرق العربي، من السومريين والبابليين حتى العصور الوسطى.",
        publisher: "دار المعرفة",
        pages: 420,
        year: 2015,
        language: "العربية",
        isbn: "994-1122334455"
    },
    {
        id: 27,
        title: "عمر بن الخطاب",
        author: "عباس العقاد",
        price: "90 جنيه",
        oldPrice: "120 جنيه",
        discount: "25%",
        image: "BOKS/صفحه الكتب/85fd1d4c-6db3-4039-8269-147a624ac7f7-192X290.jpg",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 320,
        description: "عبقرية عمر كما صورها العقاد، تتناول شخصية الفاروق الفذة وعدله وحكمه الراشد الذي أسس لدولة إسلامية قوية.",
        publisher: "دار الشروق",
        pages: 280,
        year: 2010,
        language: "العربية",
        isbn: "994-3344556677"
    },
    {
        id: 28,
        title: "تاريخ شكل تاني",
        author: "وليد فكري",
        price: "100 جنيه",
        oldPrice: "130 جنيه",
        discount: "23%",
        image: "BOKS/صفحه الكتب/219e8a04-29de-4966-8054-1a38817ae038-192X290.png",
        categories: ["تاريخ"],
        rating: 4,
        reviews: 110,
        description: "نظرة مختلفة ومبسطة لأحداث تاريخية شهيرة، بأسلوب شيق يبتعد عن السرد التقليدي الممل.",
        publisher: "دار الرواق",
        pages: 240,
        year: 2018,
        language: "العربية",
        isbn: "994-9988776655"
    },
    {
        id: 29,
        title: "البداية والنهاية",
        author: "ابن كثير",
        price: "150 جنيه",
        oldPrice: "200 جنيه",
        discount: "25%",
        image: "BOKS/Dk5AVzvUUAIw8y5.jpg",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 920,
        description: "موسوعة تاريخية ضخمة تؤرخ للعالم من بداية الخلق حتى نهايته، من أهم المراجع في التاريخ الإسلامي.",
        publisher: "دار ابن كثير",
        pages: 1200,
        year: 2001,
        language: "العربية",
        isbn: "994-7788001122"
    },
    {
        id: 30,
        title: "تاريخ الحضارات العربية",
        author: "د. فيليب حتي",
        price: "120 جنيه",
        oldPrice: "160 جنيه",
        discount: "25%",
        image: "BOKS/fbb16d224565137.Y3JvcCwxOTI0LDE1MDUsNDM4LDI5NQ.jpg",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 580,
        description: "مرجع شامل عن تاريخ العرب منذ ما قبل الإسلام حتى العصر الحديث، يتناول الحضارة والعلوم والفنون العربية.",
        publisher: "دار العلم للملايين",
        pages: 680,
        year: 1965,
        language: "العربية",
        isbn: "994-8899112233"
    },
    {
        id: 31,
        title: "الحروب الصليبية كما رآها العرب",
        author: "أمين معلوف",
        price: "80 جنيه",
        oldPrice: "110 جنيه",
        discount: "27%",
        image: "BOKS/6284f319e2413f159ddfe04db796654b.jpg",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 760,
        description: "سرد تاريخي مشوق للحروب الصليبية من المنظور العربي، يقدم صورة مختلفة عن الروايات الغربية.",
        publisher: "دار الفارابي",
        pages: 350,
        year: 1983,
        language: "العربية",
        isbn: "994-9900334455"
    },
    {
        id: 32,
        title: "مئة من عظماء أمة الإسلام",
        author: "جهاد الترباني",
        price: "95 جنيه",
        oldPrice: "130 جنيه",
        discount: "27%",
        image: "BOKS/_640x_bac78f3d53907a5d308433bf2b5bcf3ea397a4a057ff1d5554b45f1c76d01438.jpg",
        categories: ["تاريخ"],
        rating: 5,
        reviews: 440,
        description: "يستعرض سير مئة شخصية إسلامية أثرت في مجرى التاريخ، من علماء وقادة وفاتحين ومفكرين.",
        publisher: "دار التقوى",
        pages: 480,
        year: 2010,
        language: "العربية",
        isbn: "994-1122005566"
    },

    // ═══════════════════════════════════════════
    // 🧠 العلوم
    // ═══════════════════════════════════════════
    {
        id: 33,
        title: "تاريخ موجز للزمن",
        author: "ستيفن هوكينج",
        price: "70 جنيه",
        oldPrice: "100 جنيه",
        discount: "30%",
        image: "BOKS/images (1).jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 1300,
        description: "يشرح الكتاب نظريات الكون والثقوب السوداء والانفجار الكبير بأسلوب مبسط يفهمه غير المتخصصين.",
        publisher: "مكتبة جرير",
        pages: 256,
        year: 2005,
        language: "العربية",
        isbn: "994-2233116677"
    },
    {
        id: 34,
        title: "الكون - كارل ساغان",
        author: "كارل ساغان",
        price: "85 جنيه",
        oldPrice: "120 جنيه",
        discount: "29%",
        image: "BOKS/images (2).jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 980,
        description: "رحلة مذهلة عبر الكون بأسلوب علمي ساحر، يتناول تاريخ الفلك والفيزياء وموقع الإنسان في هذا الكون الشاسع.",
        publisher: "عالم المعرفة",
        pages: 370,
        year: 1993,
        language: "العربية",
        isbn: "994-3344227788"
    },
    {
        id: 35,
        title: "الخيمياء والخيميائيون",
        author: "زكي نجيب محمود",
        price: "55 جنيه",
        oldPrice: "80 جنيه",
        discount: "31%",
        image: "BOKS/images (3).jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 320,
        description: "دراسة في تاريخ العلوم عند العرب، تكشف عن إسهاماتهم العظيمة في الكيمياء والطب والرياضيات.",
        publisher: "دار المعارف",
        pages: 290,
        year: 1986,
        language: "العربية",
        isbn: "994-4455338899"
    },
    {
        id: 36,
        title: "أساسيات الفيزياء",
        author: "فريدريك بوش",
        price: "110 جنيه",
        oldPrice: "150 جنيه",
        discount: "27%",
        image: "BOKS/images (4).jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 250,
        description: "مرجع أكاديمي شامل في الفيزياء يغطي الميكانيكا والكهرباء والمغناطيسية والبصريات والفيزياء الحديثة.",
        publisher: "مكتبة العبيكان",
        pages: 650,
        year: 2012,
        language: "العربية",
        isbn: "994-5566449900"
    },
    {
        id: 37,
        title: "عالم الرياضيات المدهش",
        author: "د. أحمد فؤاد",
        price: "65 جنيه",
        oldPrice: "90 جنيه",
        discount: "28%",
        image: "BOKS/images (5).jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 180,
        description: "يكشف عن الجمال المخفي في الرياضيات ويقدمها بأسلوب مشوق من خلال ألغاز وأمثلة من الحياة اليومية.",
        publisher: "دار العلوم",
        pages: 280,
        year: 2019,
        language: "العربية",
        isbn: "994-6677550011"
    },
    {
        id: 38,
        title: "الجينات - تاريخ حميم",
        author: "سيدهارتا موخيرجي",
        price: "95 جنيه",
        oldPrice: "135 جنيه",
        discount: "30%",
        image: "BOKS/images (6).jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 420,
        description: "قصة مثيرة عن تاريخ اكتشاف الجينات والوراثة، وكيف شكلت حياتنا ومستقبلنا ومعنى أن تكون إنساناً.",
        publisher: "مكتبة جرير",
        pages: 520,
        year: 2018,
        language: "العربية",
        isbn: "994-7788661122"
    },
    {
        id: 39,
        title: "الذكاء الاصطناعي - ثورة القرن",
        author: "د. محمد الشمري",
        price: "80 جنيه",
        oldPrice: "115 جنيه",
        discount: "30%",
        image: "BOKS/images (7).jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 350,
        description: "نظرة شاملة على الذكاء الاصطناعي وتطبيقاته وتأثيره على مستقبل البشرية والتحديات الأخلاقية المرتبطة به.",
        publisher: "دار التقنية",
        pages: 340,
        year: 2023,
        language: "العربية",
        isbn: "994-8899772233"
    },
    {
        id: 40,
        title: "علم النفس التطوري",
        author: "ديفيد باس",
        price: "75 جنيه",
        oldPrice: "105 جنيه",
        discount: "29%",
        image: "BOKS/_640x_bac78f3d53907a5d308433bf2b5bcf3ea397a4a057ff1d5554b45f1c76d01438.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 290,
        description: "يستكشف الأصول التطورية للسلوك البشري وكيف شكّل الانتقاء الطبيعي عقولنا ومشاعرنا وعلاقاتنا.",
        publisher: "مكتبة العبيكان",
        pages: 460,
        year: 2016,
        language: "العربية",
        isbn: "994-9900883344"
    },
    
    {
        id: 51,
        title: "مدخل إلى علم الفلك",
        author: "د. أحمد علي",
        price: "60 جنيه",
        oldPrice: "80 جنيه",
        discount: "25%",
        image: "BOKS/science-01.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 30,
        description: "كتاب مبسط يشرح أساسيات علم الفلك والكون للمبتدئين.",
        publisher: "دار العلوم الحديثة",
        pages: 250,
        year: 2024,
        language: "العربية",
        isbn: "978-000-000000"
    },
    {
        id: 52,
        title: "رحلة في عالم الفيزياء",
        author: "د. سارة محمود",
        price: "70 جنيه",
        oldPrice: "95 جنيه",
        discount: "26%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPnak9AT2t8TlRqnFutAcq95sNbYNHVUyzLw&s",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "رحلة شيقة في أساسيات الفيزياء من الحركة إلى النسبية بأسلوب مبسط وواضح.",
        publisher: "دار المعرفة العلمية",
        pages: 320,
        year: 2022,
        language: "العربية",
        isbn: "978-000-000001"
    },
    {
        id: 53,
        title: "بيولوجيا الإنسان المبسطة",
        author: "د. منى عبد الله",
        price: "65 جنيه",
        oldPrice: "90 جنيه",
        discount: "28%",
        image: "https://cdn.salla.sa/yGRdN/04593d69-09fb-41ab-8d04-37a8ffcc0b8a-1000x1000-Vz5eKwRXY0VHQi96M3FKOMaNr1pD99CH8OCVAc9G.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "مدخل لطيف لفهم أعضاء جسم الإنسان ووظائفها مع رسوم توضيحية ملونة.",
        publisher: "دار الطب والحياة",
        pages: 280,
        year: 2021,
        language: "العربية",
        isbn: "978-000-000002"
    },
    {
        id: 54,
        title: "عجائب الكون للأطفال",
        author: "أحمد سامي",
        price: "50 جنيه",
        oldPrice: "70 جنيه",
        discount: "29%",
        image: "BOKS/science-04.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "كتاب مصور يعرّف الأطفال بالكواكب والنجوم والمجرّات بطريقة ممتعة.",
        publisher: "مكتبة الطفل العربي",
        pages: 160,
        year: 2020,
        language: "العربية",
        isbn: "978-000-000003"
    },
    {
        id: 55,
        title: "أساسيات علم الأحياء",
        author: "د. خالد حسين",
        price: "80 جنيه",
        oldPrice: "110 جنيه",
        discount: "27%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKRcq7wd3q1rBZ9VjN15mO7BGIySAt3fM1JA&s",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "مرجع مبسط في علم الأحياء يغطي الخلية والكائنات الحية والتصنيف.",
        publisher: "دار العلوم",
        pages: 340,
        year: 2019,
        language: "العربية",
        isbn: "978-000-000004"
    },
    {
        id: 56,
        title: "الكيمياء من حولنا",
        author: "د. ياسر عبد المقصود",
        price: "55 جنيه",
        oldPrice: "80 جنيه",
        discount: "31%",
        image: "BOKS/science-06.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "يشرح كيف تدخل الكيمياء في كل تفاصيل حياتنا اليومية بأسلوب بسيط.",
        publisher: "دار التجربة العلمية",
        pages: 220,
        year: 2018,
        language: "العربية",
        isbn: "978-000-000005"
    },
    {
        id: 57,
        title: "مدخل إلى علم البحار",
        author: "د. ريم سالم",
        price: "60 جنيه",
        oldPrice: "85 جنيه",
        discount: "29%",
        image: "BOKS/science-07.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "استكشاف لعالم البحار والمحيطات وما يعيش فيها من كائنات مدهشة.",
        publisher: "دار الأفق الأزرق",
        pages: 260,
        year: 2023,
        language: "العربية",
        isbn: "978-000-000006"
    },
    {
        id: 58,
        title: "الرياضيات في حياتنا اليومية",
        author: "م. عبد الرحمن فوزي",
        price: "45 جنيه",
        oldPrice: "65 جنيه",
        discount: "31%",
        image: "BOKS/science-08.jpg",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "يشرح كيف نستخدم الرياضيات بدون أن نشعر في التسوق والطبخ والعمل.",
        publisher: "دار التميز",
        pages: 190,
        year: 2021,
        language: "العربية",
        isbn: "978-000-000007"
    },
    {
        id: 59,
        title: "مقدمة في علم الحاسوب",
        author: "م. وليد عبد العزيز",
        price: "75 جنيه",
        oldPrice: "100 جنيه",
        discount: "25%",
        image: "https://static.abuelfateh.com/imgs/1920x1080/introduction-about-computer-science.webp",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "مدخل مبسط لأساسيات علم الحاسوب والخوارزميات وأنظمة التشغيل.",
        publisher: "دار التقنية الحديثة",
        pages: 300,
        year: 2022,
        language: "العربية",
        isbn: "978-000-000008"
    },
    {
        id: 60,
        title: "علم الفضاء واستكشاف الكواكب",
        author: "د. حسين جابر",
        price: "85 جنيه",
        oldPrice: "115 جنيه",
        discount: "26%",
        image: "https://afdne-bo.s3.ap-south-1.amazonaws.com/images/7366170697781565be6a1751c58.jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "يروي قصة سباق الفضاء وأهم المهام الفضائية واكتشاف الكواكب البعيدة.",
        publisher: "عالم المعرفة",
        pages: 360,
        year: 2020,
        language: "العربية",
        isbn: "978-000-000009"
    },
    {
        id: 61,
        title: "عالم الحشرات الغريب",
        author: "د. نجلاء أحمد",
        price: "55 جنيه",
        oldPrice: "75 جنيه",
        discount: "27%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUuVYAufYkOZvU3sHvl9e0XIwOWpbKzGZgAg&s",
        categories: ["علوم"],
        rating: 3,
        reviews: 10,
        description: "يتناول حياة الحشرات وتنوعها وأدوارها في النظام البيئي.",
        publisher: "دار البيئة",
        pages: 210,
        year: 2019,
        language: "العربية",
        isbn: "978-000-000010"
    },
    {
        id: 62,
        title: "موسوعة جسم الإنسان المصورة",
        author: "مجموعة مؤلفين",
        price: "120 جنيه",
        oldPrice: "160 جنيه",
        discount: "25%",
        image: "https://apis.takweenkw.com/Attachments/book//2020070112293737996135.png",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "موسوعة مصورة تشرح أجهزة جسم الإنسان ووظائفها بالتفصيل.",
        publisher: "دار الموسوعات",
        pages: 480,
        year: 2018,
        language: "العربية",
        isbn: "978-000-000011"
    },
    {
        id: 63,
        title: "مدخل إلى علم الجينات",
        author: "د. هدى صبري",
        price: "90 جنيه",
        oldPrice: "125 جنيه",
        discount: "28%",
        image: "https://nohoudh-center.com/sites/default/files/styles/large_16_9/public/2024-01/WhatsApp%20Image%202024-01-08%20at%2015.07.08_12f493fa.jpg?itok=Cd4m0IR8",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "يقدّم أساسيات علم الوراثة والجينات والتطبيقات الطبية الحديثة.",
        publisher: "دار الجينات",
        pages: 340,
        year: 2023,
        language: "العربية",
        isbn: "978-000-000012"
    },
    {
        id: 64,
        title: "الفيزياء النووية المبسطة",
        author: "د. محمد فاضل",
        price: "95 جنيه",
        oldPrice: "130 جنيه",
        discount: "27%",
        image: "https://www.noor-book.com/publice/covers_cache_webp/18/9/2/7/c0cf45fb259275540ba718cd856d6cf7.jpg.webp",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "شرح مبسط لمفاهيم الفيزياء النووية والطاقة الذرية وتطبيقاتها.",
        publisher: "دار الطاقة",
        pages: 310,
        year: 2017,
        language: "العربية",
        isbn: "978-000-000013"
    },
    {
        id: 65,
        title: "الذكاء الاصطناعي في حياتنا",
        author: "م. رائد الشمري",
        price: "80 جنيه",
        oldPrice: "110 جنيه",
        discount: "27%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6UI2U5V3-Xtgl5zRfGOxZWQOrwiOj2AgfMQ&s",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "يتناول تطبيقات الذكاء الاصطناعي في الطب والتعليم والاقتصاد.",
        publisher: "دار التقنية",
        pages: 270,
        year: 2024,
        language: "العربية",
        isbn: "978-000-000014"
    },
    {
        id: 66,
        title: "الطاقة المتجددة ومستقبل الكوكب",
        author: "د. ليلى فؤاد",
        price: "75 جنيه",
        oldPrice: "105 جنيه",
        discount: "29%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtKw1k3NB5PAhXmraCUvhwychifPXuW8emYw&s",
        categories: ["علوم"],
        rating: 4,
        reviews: 20,
        description: "يتحدث عن مصادر الطاقة المتجددة ودورها في حماية البيئة.",
        publisher: "دار المستقبل الأخضر",
        pages: 260,
        year: 2021,
        language: "العربية",
        isbn: "978-000-000015"
    },
    {
        id: 67,
        title: "عالم الديناصورات المفقود",
        author: "د. مازن حجازي",
        price: "60 جنيه",
        oldPrice: "85 جنيه",
        discount: "29%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg42vgIBmi6x0dGmlKiS0DUhYG7pcsP7SZ2g&s",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "يتناول تاريخ الديناصورات وأنواعها وكيفية انقراضها.",
        publisher: "دار التاريخ الطبيعي",
        pages: 230,
        year: 2016,
        language: "العربية",
        isbn: "978-000-000016"
    },
    {
        id: 68,
        title: "المخ البشري وأسرار العقل",
        author: "د. فاطمة الشربيني",
        price: "90 جنيه",
        oldPrice: "120 جنيه",
        discount: "25%",
        image: "https://diwanegypt.com/wp-content/uploads/2022/03/9789777814829.jpg",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "يستكشف تركيب المخ البشري ووظائفه وما توصل إليه العلم الحديث.",
        publisher: "دار علم الأعصاب",
        pages: 360,
        year: 2022,
        language: "العربية",
        isbn: "978-000-000017"
    },
    {
        id: 69,
        title: "البيئة والتغيّر المناخي",
        author: "د. سامر أشرف",
        price: "70 جنيه",
        oldPrice: "95 جنيه",
        discount: "26%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHlEoIyofJqW8vK5lQc5A49G9jB8t0uyQnhQ&s",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "شرح لأسباب التغير المناخي وتأثيره على الكوكب وطرق مواجهته.",
        publisher: "دار البيئة المعاصرة",
        pages: 280,
        year: 2020,
        language: "العربية",
        isbn: "978-000-000018"
    },
    {
        id: 70,
        title: "مدخل إلى علم الفلك الرصدي",
        author: "م. حازم نبيل",
        price: "89 جنيه",
        oldPrice: "115 جنيه",
        discount: "26%",
        image: " https://www.noor-book.com/publice/covers_cache_webp/18/6/e/8/d61b43bed26e8d2afb4b0f1f90231b15.jpg.webp",
        categories: ["علوم"],
        rating: 5,
        reviews: 0,
        description: "دليل عملي لاستخدام التلسكوبات ورصد السماء ليلاً للهواة.",
        publisher: "نادي الفلك العربي",
        pages: 300,
        year: 2023,
        language: "العربية",
        isbn: "978-000-000019"
    },
    {
        id: 71,
        title: "الرياضيات الممتعة بالألغاز",
        author: "د. عمرو إبراهيم",
        price: "50 جنيه",
        oldPrice: "75 جنيه",
        discount: "33%",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfWApqgVOoHsvJva5VCGUkgZ6IBOZ9TU7Q-Q&s",
        categories: ["علوم"],
        rating: 4,
        reviews: 0,
        description: "مجموعة من الألغاز والتمارين التي تجعل تعلم الرياضيات ممتعاً.",
        publisher: "دار الألغاز العلمية",
        pages: 200,
        year: 2021,
        language: "العربية",
        isbn: "978-000-000020"
    },

    // ═══════════════════════════════════════════
    // ✒️ الأدب والشعر
    // ═══════════════════════════════════════════
    {
        id: 41,
        title: "ديوان المتنبي",
        author: "أبو الطيب المتنبي",
        price: "100 جنيه",
        oldPrice: "140 جنيه",
        discount: "29%",
        image: "BOKS/images (1).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 680,
        description: "ديوان أمير الشعراء العرب، يضم أشهر القصائد في الحكمة والفخر والمديح والهجاء، تراث أدبي خالد.",
        publisher: "دار صادر",
        pages: 480,
        year: 1990,
        language: "العربية",
        isbn: "994-1100994455"
    },
    {
        id: 42,
        title: "طوق الحمامة",
        author: "ابن حزم الأندلسي",
        price: "65 جنيه",
        oldPrice: "90 جنيه",
        discount: "28%",
        image: "BOKS/images (2).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 520,
        description: "رسالة في الحب والعشق بأسلوب أدبي رفيع، يمزج بين الشعر والنثر ويحلل مشاعر الحب بعمق فلسفي.",
        publisher: "دار المعارف",
        pages: 260,
        year: 1985,
        language: "العربية",
        isbn: "994-2211005566"
    },
    {
        id: 43,
        title: "المعلقات السبع - شرح الزوزني",
        author: "الزوزني",
        price: "80 جنيه",
        oldPrice: "110 جنيه",
        discount: "27%",
        image: "BOKS/images (3).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 410,
        description: "شرح مفصل للمعلقات السبع الشهيرة، أرقى ما أنتجه الشعر العربي الجاهلي، مع تحليل لغوي وبلاغي.",
        publisher: "دار المعرفة",
        pages: 320,
        year: 2000,
        language: "العربية",
        isbn: "994-3322116677"
    },
    {
        id: 44,
        title: "الأغاني - مختارات",
        author: "أبو الفرج الأصفهاني",
        price: "130 جنيه",
        oldPrice: "180 جنيه",
        discount: "28%",
        image: "BOKS/images (4).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 340,
        description: "مختارات من موسوعة الأغاني الشهيرة، تضم أخبار الشعراء والمغنين وقصائدهم في العصور العربية المختلفة.",
        publisher: "دار الكتب العلمية",
        pages: 560,
        year: 1995,
        language: "العربية",
        isbn: "994-4433227788"
    },
    {
        id: 45,
        title: "ديوان نزار قباني - الأعمال الكاملة",
        author: "نزار قباني",
        price: "140 جنيه",
        oldPrice: "190 جنيه",
        discount: "26%",
        image: "BOKS/images (5).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 870,
        description: "الأعمال الشعرية الكاملة لشاعر الحب والمرأة والوطن، تتنوع بين الغزل والسياسة والأشعار الوجدانية.",
        publisher: "منشورات نزار قباني",
        pages: 720,
        year: 1998,
        language: "العربية",
        isbn: "994-5544338899"
    },
    {
        id: 46,
        title: "البؤساء - ملخص ومختارات",
        author: "فيكتور هوجو",
        price: "90 جنيه",
        oldPrice: "125 جنيه",
        discount: "28%",
        image: "BOKS/images (6).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 640,
        description: "مختارات من رائعة فيكتور هوجو الأدبية التي تتناول قصة الفقر والعدالة والتضحية في فرنسا القرن التاسع عشر.",
        publisher: "دار الترجمة العربية",
        pages: 450,
        year: 2008,
        language: "العربية",
        isbn: "994-6655449900"
    },
    {
        id: 47,
        title: "النبي",
        author: "جبران خليل جبران",
        price: "45 جنيه",
        oldPrice: "70 جنيه",
        discount: "36%",
        image: "BOKS/images (7).jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 1100,
        description: "تحفة أدبية فلسفية تتحدث عن الحب والزواج والأبناء والعمل والحرية بأسلوب شعري فريد خالد عبر الزمن.",
        publisher: "دار الجيل",
        pages: 120,
        year: 1923,
        language: "العربية",
        isbn: "994-7766550011"
    },
    {
        id: 48,
        title: "رسائل غسان كنفاني إلى غادة السمان",
        author: "غسان كنفاني",
        price: "50 جنيه",
        oldPrice: "75 جنيه",
        discount: "33%",
        image: "BOKS/Dk5AVzvUUAIw8y5.jpg",
        categories: ["أدب وشعر"],
        rating: 5,
        reviews: 490,
        description: "مجموعة رسائل عاطفية وأدبية بين أديبين عربيين كبيرين، تكشف جانبًا إنسانيًا عميقًا من حياة غسان كنفاني.",
        publisher: "دار المنشورات العربية",
        pages: 180,
        year: 1992,
        language: "العربية",
        isbn: "994-8877661122"
    },
    {
        id: 49,
        title: "الذكاء الاصطناعي والمستقبل",
        author: "د. سامي مسعود",
        price: "150 جنيه",
        oldPrice: "200 جنيه",
        discount: "25%",
        image: "BOKS/3edb9eb5-83e9-4e5c-bd07-88baae93fa22.jpg",
        categories: ["علوم", "تنمية بشرية"],
        rating: 5,
        reviews: 320,
        description: "في هذا الكتاب نستكشف كيف ستؤثر تقنيات الذكاء الاصطناعي على مختلف جوانب الحياة المستقبلية من التعليم للطب والاقتصاد.",
        publisher: "عالم المعرفة",
        pages: 350,
        year: 2024,
        language: "العربية",
        isbn: "978-994-001002"
    },
    {
        id: 50,
        title: "قصة نجاح - كيف تبني إمبراطوريتك",
        author: "إيهاب فكري",
        price: "45 جنيه",
        oldPrice: null,
        discount: null,
        image: "BOKS/صفحه الكتب/8ed63bf9-18af-48a6-bee2-6014ba3c69a6-192X290.png",
        categories: ["تنمية بشرية"],
        rating: 4,
        reviews: 145,
        description: "دليلك الشامل لتبدأ من الصفر حتى تبني مشروع أحلامك بخطوات عملية ونصائح من واقع السوق.",
        publisher: "دار النجاح",
        pages: 200,
        year: 2023,
        language: "العربية",
        isbn: "978-123-002008"
    },
];
